version: '3'
services:
  object-classification:
    restart: always
    image: lumas/lumas-object-detection
    network_mode: host
    volumes:
      - ./logs:/app/logs
  controller:
    restart: always
    image: lumas/lumas-controller
    network_mode: host
    volumes:
      - ./logs:/app/logs
